# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d83aeb34f98da11a8511b240031d403f6e8b5482194d3befa17ce24582fc57dfcea9c61c2a7170b0b9bc8bc53e3c6c1ce81d857d50ceb020d428a39499f2614e
  twitter_api_key: X5hfuDaBnplYCZ1OrE1Z5MyiX
  twitter_api_secret: rzXKlX0RDIhLi5y0zX3KErqvPZVxrxnr2DZMTfM81QNp9WJPnd
  facebook_api_key: '1859523560940609'
  facebook_api_secret: 'c58055c0daafe00ddf46056a8f6c67f0'

test:
  secret_key_base: af9f6dd312e2fdc639e2cb375efa6fe6c436b1e91bbffb40045c80c75430b2b1f0a6017406a065ba20b71dcfa546385a8f462e174589e08befa54a64099bfab4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
